#include <amxmodx>
#include <fakemeta>
#include <efk_const>

new const PLUGIN[] = "EFK: UnPrecacher"

new const UNPRECACHE_SOUNDS[][] =
{
	"shield",
	"hostage/hos1.wav",
	"hostage/hos2.wav",
	"hostage/hos3.wav",
	"hostage/hos4.wav",
	"hostage/hos5.wav",
	"items/equip_nvg.wav",
	"items/kevlar.wav",
	"items/nvg_off.wav",
	"items/nvg_on.wav",
	"items/tr_kevlar.wav",
	"plats/vehicle1.wav",
	"plats/vehicle2.wav",
	"plats/vehicle3.wav",
	"plats/vehicle4.wav",
	"plats/vehicle6.wav",
	"plats/vehicle7.wav",
	"plats/vehicle_brake1.wav",
	"plats/vehicle_ignition.wav",
	"plats/vehicle_start1.wav",
	"radio",
	"weapons/ak47-1.wav",
	"weapons/ak47-2.wav",
	"weapons/ak47_boltpull.wav",
	"weapons/ak47_clipin.wav",
	"weapons/ak47_clipout.wav",
	"weapons/aug-1.wav",
	"weapons/aug_boltpull.wav",
	"weapons/aug_boltslap.wav",
	"weapons/aug_clipin.wav",
	"weapons/aug_clipout.wav",
	"weapons/aug_forearm.wav",
	"weapons/awp1.wav",
	"weapons/awp_clipin.wav",
	"weapons/awp_clipout.wav",
	"weapons/awp_deploy.wav",
	"weapons/boltdown.wav",
	"weapons/boltpull1.wav",
	"weapons/boltup.wav",
	"weapons/c4_beep1.wav",
	"weapons/c4_beep2.wav",
	"weapons/c4_beep3.wav",
	"weapons/c4_beep4.wav",
	"weapons/c4_beep5.wav",
	"weapons/c4_click.wav",
	"weapons/c4_disarm.wav",
	"weapons/c4_disarmed.wav",
	"weapons/c4_explode1.wav",
	"weapons/c4_plant.wav",
	"weapons/clipin1.wav",
	"weapons/clipout1.wav",
	"weapons/de_clipin.wav",
	"weapons/de_clipout.wav",
	"weapons/de_deploy.wav",
	"weapons/deagle-1.wav",
	"weapons/deagle-2.wav",
	"weapons/dryfire_pistol.wav",
	"weapons/dryfire_rifle.wav",
	"weapons/elite_clipout.wav",
	"weapons/elite_deploy.wav",
	"weapons/elite_fire.wav",
	"weapons/elite_leftclipin.wav",
	"weapons/elite_reloadstart.wav",
	"weapons/elite_rightclipin.wav",
	"weapons/elite_sliderelease.wav",
	"weapons/elite_twirl.wav",
	"weapons/famas-1.wav",
	"weapons/famas-2.wav",
	"weapons/famas-burst.wav",
	"weapons/famas_boltpull.wav",
	"weapons/famas_boltslap.wav",
	"weapons/famas_clipin.wav",
	"weapons/famas_clipout.wav",
	"weapons/famas_forearm.wav",
	"weapons/fiveseven-1.wav",
	"weapons/fiveseven_clipin.wav",
	"weapons/fiveseven_clipout.wav",
	"weapons/fiveseven_slidepull.wav",
	"weapons/fiveseven_sliderelease.wav",
	"weapons/g3sg1-1.wav",
	"weapons/g3sg1_clipin.wav",
	"weapons/g3sg1_clipout.wav",
	"weapons/g3sg1_slide.wav",
	"weapons/galil-1.wav",
	"weapons/galil-2.wav",
	"weapons/galil_boltpull.wav",
	"weapons/galil_clipin.wav",
	"weapons/galil_clipout.wav",
	"weapons/generic_reload.wav",
	"weapons/generic_shot_reload.wav",
	"weapons/glock18-1.wav",
	"weapons/glock18-2.wav",
	"weapons/headshot2.wav",
	"weapons/m3-1.wav",
	"weapons/m3_insertshell.wav",
	"weapons/m3_pump.wav",
	"weapons/m4a1-1.wav",
	"weapons/m4a1_boltpull.wav",
	"weapons/m4a1_clipin.wav",
	"weapons/m4a1_clipout.wav",
	"weapons/m4a1_deploy.wav",
	"weapons/m4a1_silencer_off.wav",
	"weapons/m4a1_silencer_on.wav",
	"weapons/m4a1_unsil-1.wav",
	"weapons/m4a1_unsil-2.wav",
	"weapons/m249-1.wav",
	"weapons/m249-2.wav",
	"weapons/m249_boxin.wav",
	"weapons/m249_boxout.wav",
	"weapons/m249_chain.wav",
	"weapons/m249_coverdown.wav",
	"weapons/m249_coverup.wav",
	"weapons/mac10-1.wav",
	"weapons/mac10_boltpull.wav",
	"weapons/mac10_clipin.wav",
	"weapons/mac10_clipout.wav",
	"weapons/mp5-1.wav",
	"weapons/mp5-2.wav",
	"weapons/mp5_clipin.wav",
	"weapons/mp5_clipout.wav",
	"weapons/mp5_slideback.wav",
	"weapons/p90-1.wav",
	"weapons/p90_boltpull.wav",
	"weapons/p90_clipin.wav",
	"weapons/p90_clipout.wav",
	"weapons/p90_cliprelease.wav",
	"weapons/p228-1.wav",
	"weapons/p228_clipin.wav",
	"weapons/p228_clipout.wav",
	"weapons/p228_slidepull.wav",
	"weapons/p228_sliderelease.wav",
	"weapons/pinpull.wav",
	"weapons/ric_conc-1.wav",
	"weapons/ric_conc-2.wav",
	"weapons/ric_metal-1.wav",
	"weapons/ric_metal-2.wav",
	"weapons/scout_bolt.wav",
	"weapons/scout_clipin.wav",
	"weapons/scout_clipout.wav",
	"weapons/scout_fire-1.wav",
	"weapons/sg550-1.wav",
	"weapons/sg550_boltpull.wav",
	"weapons/sg550_clipin.wav",
	"weapons/sg550_clipout.wav",
	"weapons/sg552-1.wav",
	"weapons/sg552-2.wav",
	"weapons/sg552_boltpull.wav",
	"weapons/sg552_clipin.wav",
	"weapons/sg552_clipout.wav",
	"weapons/slideback1.wav",
	"weapons/sliderelease1.wav",
	"weapons/tmp-1.wav",
	"weapons/tmp-2.wav",
	"weapons/ump45-1.wav",
	"weapons/ump45_boltslap.wav",
	"weapons/ump45_clipin.wav",
	"weapons/ump45_clipout.wav",
	"weapons/usp1.wav",
	"weapons/usp2.wav",
	"weapons/usp_clipin.wav",
	"weapons/usp_clipout.wav",
	"weapons/usp_silencer_off.wav",
	"weapons/usp_silencer_on.wav",
	"weapons/usp_slideback.wav",
	"weapons/usp_sliderelease.wav",
	"weapons/usp_unsil-1.wav",
	"weapons/xm1014-1.wav",
	"weapons/zoom.wav"
}

new const UNPRECACHE_MODELS[][] =
{
	"models/p_ak47.mdl",
	"models/p_aug.mdl",
	"models/p_awp.mdl",
	"models/p_c4.mdl",
	"models/p_deagle.mdl",
	"models/p_elite.mdl",
	"models/p_famas.mdl",
	"models/p_fiveseven.mdl",
	"models/p_g3sg1.mdl",
	"models/p_galil.mdl",
	"models/p_m3.mdl",
	"models/p_m3super90.mdl",
	"models/p_m4a1.mdl",
	"models/p_m249.mdl",
	"models/p_mac10.mdl",
	"models/p_mp5.mdl",
	"models/p_p90.mdl",
	"models/p_p228.mdl",
	"models/p_scout.mdl",
	"models/p_sg550.mdl",
	"models/p_sg552.mdl",
	"models/p_shield.mdl",
	"models/p_tmp.mdl",
	"models/p_ump45.mdl",
	"models/p_xm1014.mdl",
	"models/v_ak47.mdl",
	"models/v_aug.mdl",
	"models/v_awp.mdl",
	"models/v_c4.mdl",
	"models/v_deagle.mdl",
	"models/v_elite.mdl",
	"models/v_famas.mdl",
	"models/v_fiveseven.mdl",
	"models/v_g3sg1.mdl",
	"models/v_galil.mdl",
	"models/v_knife_r.mdl",
	"models/v_m3.mdl",
	"models/v_m4a1.mdl",
	"models/v_m249.mdl",
	"models/v_mac10.mdl",
	"models/v_mp5.mdl",
	"models/v_p90.mdl",
	"models/v_p228.mdl",
	"models/v_scout.mdl",
	"models/v_sg550.mdl",
	"models/v_sg552.mdl",
	"models/v_shield_r.mdl",
	"models/v_tmp.mdl",
	"models/v_ump45.mdl",
	"models/v_xm1014.mdl"
}

public plugin_init()
{
	register_plugin(PLUGIN, EFK_VERSION, "Next21 Team")
}

public plugin_precache()
{
	register_forward(FM_PrecacheSound, "FM_PrecacheSound_Pre")
	register_forward(FM_PrecacheModel, "FM_PrecacheModel_Pre")
}

public FM_PrecacheSound_Pre(const szSound[])
{
	for (new i; i < sizeof(UNPRECACHE_SOUNDS); i++)
	{
		if (contain(szSound, UNPRECACHE_SOUNDS[i]) != -1)
			return FMRES_SUPERCEDE
	}

	return FMRES_IGNORED
}

public FM_PrecacheModel_Pre(const szModel[])
{
	for (new i; i < sizeof(UNPRECACHE_MODELS); i++)
	{
		if (contain(szModel, UNPRECACHE_MODELS[i]) != -1)
			return FMRES_SUPERCEDE
	}

	return FMRES_IGNORED
}
