; Core
efk_core.amxx
efk_unprecacher.amxx

; Knives
efk_knife_blink.amxx
efk_knife_slap.amxx
efk_knife_flash.amxx
efk_knife_ninja.amxx
efk_knife_leap.amxx
efk_knife_fire.amxx
efk_knife_nuclear.amxx
efk_knife_frost.amxx
efk_knife_thunder.amxx
efk_knife_razor.amxx
efk_knife_telekinesis.amxx
efk_knife_swap.amxx
efk_knife_necro.amxx
efk_knife_spikes.amxx
efk_knife_dark.amxx
efk_knife_acidtrap.amxx
efk_knife_tentacles.amxx
efk_knife_creepy.amxx
efk_knife_wind.amxx
efk_knife_water.amxx

; Items
efk_item_frost_fire_gas.amxx
efk_item_he.amxx
efk_item_flash.amxx
efk_item_hp.amxx
efk_item_hp-scan.amxx
efk_item_hs.amxx
efk_item_crits.amxx
efk_item_vampirism.amxx
efk_item_regeneration.amxx
efk_item_bunny.amxx
efk_item_chargebooster.amxx

; Stats
efk_statsx_sql.amxx
efk_statsx_aes.amxx

; Extra
efk_balancer.amxx
efk_deathmatch.amxx
efk_hats.amxx
efk_presents.amxx
efk_dominations.amxx
efk_duels.amxx
efk_sayme.amxx
efk_damage_table.amxx
efk_radioblock.amxx
efk_nextclient_features.amxx
addon_floating_damage.amxx
next21_save_spec_money.amxx
